local E, L, C = unpack(select(2, ...))

local name = "ElvDB"
local profile = {
	["Cannon"] = {
		["Enabled"] = true,
		["Timer102116Cannon0"] = true,
		["Play countdown sound for $spell:102116"] = true,
		["Announce"] = false,
	},
	["PlantsVsZombies"] = {
		["Create Aberration"] = true,
		["Create Zombie"] = false,
		["Create Abomination"] = true,
		["Create Ghoul"] = false,
		["warnTotalAdds"] = true,
		["specWarnWave"] = true,
		["Announce"] = false,
		["Enabled"] = true,
	},
	["Rabbit"] = {
		["Enabled"] = true,
		["HUGE, SHARP TEETH! on >%s<"] = true,
		["HealthFrame"] = false,
		["Announce"] = false,
		["SpeedKillTimer"] = false,
		["Yell when you are affected by $spell:114078"] = true,
	},
	["Greench"] = {
		["Enabled"] = true,
		["Throw Strange Snowman"] = true,
		["HealthFrame"] = false,
		["Timer101885Greench3"] = true,
		["Throw Winter Veil Tree"] = true,
		["Timer101907Greench4"] = true,
		["Casting Snow Crash: 5.0 sec"] = true,
		["Announce"] = false,
		["Timer101938Greench2"] = true,
		["Timer101873Greench0"] = true,
		["Timer101910Greench1"] = true,
		["Shrink Heart - move away"] = true,
		["SpeedKillTimer"] = false,
		["Shrink Heart"] = true,
	},
	["Gnoll"] = {
		["Enabled"] = true,
		["warnHogger"] = true,
		["specWarnHogger"] = true,
		["warnGameOver"] = true,
		["warnGnoll"] = false,
		["Play countdown sound for $spell:101612"] = true,
		["Announce"] = false,
		["Timer101612Gnoll0"] = true,
	},
	["CorenDirebrew"] = {
		["Enabled"] = true,
		["HealthFrame"] = false,
		["Barreled! on >%s<"] = true,
		["Timer47340CorenDirebrew2"] = true,
		["YellOnBarrel"] = false,
		["specWarnBrewStun"] = true,
		["SpeedKillTimer"] = false,
		["Timer47310CorenDirebrew3"] = true,
		["Casting Direbrew's Disarm: 4.0 sec"] = true,
		["specWarnBrew"] = true,
		["Timer51413CorenDirebrew0"] = true,
		["Announce"] = false,
		["Timer47376CorenDirebrew1"] = true,
	},
	["Shot"] = {
		["Enabled"] = true,
		["Play countdown sound for $spell:101871"] = true,
		["Announce"] = false,
		["Timer101871Shot0"] = true,
		["SetBubbles"] = true,
	},
	["HeadlessHorseman"] = {
		["Enabled"] = true,
		["warnHorsemanSoldiers"] = true,
		["HealthFrame"] = false,
		["Timer42380HeadlessHorseman1"] = true,
		["WarnPhase"] = true,
		["Timer42514HeadlessHorseman2"] = true,
		["Announce"] = false,
		["warnHorsemanHead"] = true,
		["TimerCombatStart"] = true,
		["Conflagration on >%s<"] = true,
		["SpeedKillTimer"] = false,
		["Record Kill"] = true,
		["Squash Soul on >%s<"] = true,
	},
	["Tonks"] = {
		["Enabled"] = true,
		["Play \"run away\" sound for $spell:102341"] = true,
		["Marked! - run away"] = true,
		["Play countdown sound for $spell:102178"] = true,
		["Marked!"] = true,
		["Announce"] = false,
		["Timer102178Tonks0"] = true,
	},
	["ApothecaryTrio"] = {
		["Enabled"] = true,
		["TrioActiveTimer"] = true,
		["HealthFrame"] = false,
		["Casting Chain Reaction: 3.0 sec"] = true,
		["Timer68821ApothecaryTrio3"] = true,
		["Concentrated Irresistible Cologne Spill - move away"] = true,
		["Concentrated Alluring Perfume Spill - move away"] = true,
		["Announce"] = false,
		["SpeedKillTimer"] = false,
	},
	["Omen"] = {
		["Enabled"] = true,
		["Timer104903Omen0"] = true,
		["HealthFrame"] = false,
		["Starfall"] = true,
		["Announce"] = false,
		["Omen - Cleave"] = true,
		["Timer26540Omen1"] = true,
		["SpeedKillTimer"] = false,
		["Starfall - move away"] = true,
	},
	["Ahune"] = {
		["Enabled"] = true,
		["specWarnAttack"] = true,
		["HealthFrame"] = false,
		["SubmergTimer"] = true,
		["Emerged"] = true,
		["TimerCombat"] = true,
		["EmergeTimer"] = true,
		["Announce"] = false,
		["SpeedKillTimer"] = false,
		["Submerged"] = true,
	},
}

E:RegisterProfile(name, profile)
