local E, L, C = unpack(select(2, ...))

local name = "MSBTProfiles_SavedVars"
local profile = {
	["profiles"] = {
		["cidarhalm"] = {
			["normalFontSize"] = 15,
			["critOutlineIndex"] = 2,
			["critFontName"] = "Calibri v0.9",
			["normalOutlineIndex"] = 2,
			["scrollAreas"] = {
				["Static"] = {
					["critFontSize"] = 22,
					["offsetY"] = 33,
					["offsetX"] = -19,
					["normalFontSize"] = 18,
				},
				["Notification"] = {
					["scrollHeight"] = 115,
					["offsetY"] = -122,
					["offsetX"] = -170,
					["normalFontSize"] = 22,
				},
				["Outgoing"] = {
					["direction"] = "Up",
					["offsetX"] = -591,
					["scrollHeight"] = 160,
					["stickyBehavior"] = "Normal",
					["offsetY"] = -243,
					["behavior"] = "CurvedLeft",
					["normalFontSize"] = 18,
				},
				["Incoming"] = {
					["critFontSize"] = 26,
					["scrollHeight"] = 160,
					["offsetX"] = 541,
					["behavior"] = "CurvedRight",
					["stickyBehavior"] = "Normal",
					["offsetY"] = -243,
					["stickyDirection"] = "Up",
					["normalFontSize"] = 18,
				},
			},
			["normalFontName"] = "Calibri v0.9",
			["soundsDisabled"] = true,
			["creationVersion"] = "5.3.36",
		},
		["annai"] = {
			["normalFontSize"] = 15,
			["normalOutlineIndex"] = 2,
			["soundsDisabled"] = true,
			["critOutlineIndex"] = 2,
			["scrollAreas"] = {
				["Incoming"] = {
					["critFontSize"] = 26,
					["scrollHeight"] = 160,
					["offsetX"] = 432,
					["stickyBehavior"] = "Normal",
					["offsetY"] = -243,
					["behavior"] = "CurvedRight",
					["normalFontSize"] = 18,
				},
				["Static"] = {
					["critFontSize"] = 22,
					["offsetY"] = 33,
					["offsetX"] = -19,
					["normalFontSize"] = 18,
				},
				["Outgoing"] = {
					["scrollHeight"] = 160,
					["offsetX"] = -465,
					["direction"] = "Up",
					["stickyBehavior"] = "Normal",
					["offsetY"] = -243,
					["behavior"] = "CurvedLeft",
					["normalFontSize"] = 18,
				},
				["Notification"] = {
					["offsetY"] = -122,
					["scrollHeight"] = 115,
					["offsetX"] = -170,
					["normalFontSize"] = 22,
				},
			},
			["normalFontName"] = "Calibri v0.9",
			["critFontName"] = "Calibri v0.9",
			["creationVersion"] = "5.3.36",
		},
		["Default"] = {
			["creationVersion"] = "5.3.36",
			["critFontName"] = "ElvUI Font",
			["normalOutlineIndex"] = 2,
			["scrollAreas"] = {
				["Incoming"] = {
					["critFontAlpha"] = 100,
					["critFontName"] = "ElvUI Font",
					["direction"] = "Up",
					["critFontSize"] = 15,
					["scrollHeight"] = 100,
					["offsetX"] = -352,
					["stickyDirection"] = "Up",
					["normalFontAlpha"] = 100,
					["offsetY"] = -514,
					["normalFontName"] = "ElvUI Font",
					["normalFontSize"] = 15,
				},
				["Custom2"] = {
					["direction"] = "Alternate",
					["critFontName"] = "ElvUI Font",
					["behavior"] = "GrowUp",
					["disabled"] = true,
					["name"] = "Misses",
					["offsetX"] = -525,
					["normalFontName"] = "ElvUI Font",
					["normalFontAlpha"] = 100,
					["offsetY"] = -229,
					["animationStyle"] = "Horizontal",
					["normalFontSize"] = 16,
				},
				["Notification"] = {
					["direction"] = "Up",
					["critFontName"] = "ElvUI Font",
					["critFontSize"] = 15,
					["scrollHeight"] = 50,
					["offsetX"] = -182,
					["disabled"] = true,
					["normalFontName"] = "ElvUI Font",
					["offsetY"] = -383,
					["animationStyle"] = "Static",
					["normalFontSize"] = 15,
				},
				["Static"] = {
					["direction"] = "Up",
					["critFontName"] = "ElvUI Font",
					["skillIconsDisabled"] = true,
					["critFontSize"] = 22,
					["scrollHeight"] = 50,
					["offsetX"] = 188,
					["disabled"] = true,
					["normalFontAlpha"] = 100,
					["normalFontName"] = "ElvUI Font",
					["offsetY"] = -486,
					["normalFontSize"] = 15,
				},
				["Custom1"] = {
					["name"] = "Outgoing",
					["critFontName"] = "ElvUI Font",
					["disabled"] = true,
					["normalFontAlpha"] = 100,
					["normalFontName"] = "ElvUI Font",
					["offsetY"] = 0,
					["offsetX"] = 0,
				},
				["Outgoing"] = {
					["direction"] = "Up",
					["critFontName"] = "ElvUI Font",
					["critOutlineIndex"] = 2,
					["normalOutlineIndex"] = 2,
					["critFontAlpha"] = 100,
					["offsetY"] = -513,
					["critFontSize"] = 15,
					["scrollHeight"] = 100,
					["name"] = "Crits Only",
					["offsetX"] = 363,
					["normalFontAlpha"] = 100,
					["normalFontName"] = "ElvUI Font",
					["textAlignIndex"] = 2,
					["normalFontSize"] = 15,
				},
			},
			["soundsDisabled"] = true,
			["critOutlineIndex"] = 2,
			["normalFontSize"] = 15,
		},
		["Saonserey"] = {
			["critFontName"] = "Calibri v0.9",
			["normalOutlineIndex"] = 2,
			["creationVersion"] = "5.3.36",
			["normalFontSize"] = 15,
			["soundsDisabled"] = true,
			["events"] = {
				["INCOMING_SPELL_INTERRUPT"] = {
					["scrollArea"] = "Notification",
				},
			},
			["scrollAreas"] = {
				["Static"] = {
					["critFontSize"] = 22,
					["offsetY"] = 33,
					["offsetX"] = -19,
					["normalFontSize"] = 18,
				},
				["Notification"] = {
					["scrollHeight"] = 115,
					["offsetY"] = -122,
					["offsetX"] = -170,
					["normalFontSize"] = 22,
				},
				["Outgoing"] = {
					["direction"] = "Up",
					["offsetX"] = -465,
					["scrollHeight"] = 160,
					["stickyBehavior"] = "Normal",
					["offsetY"] = -243,
					["behavior"] = "CurvedLeft",
					["normalFontSize"] = 18,
				},
				["Incoming"] = {
					["critFontSize"] = 26,
					["scrollHeight"] = 160,
					["offsetX"] = 432,
					["stickyBehavior"] = "Normal",
					["offsetY"] = -243,
					["behavior"] = "CurvedRight",
					["normalFontSize"] = 18,
				},
			},
			["normalFontName"] = "Calibri v0.9",
			["critOutlineIndex"] = 2,
			["qualityExclusions"] = {
				true, -- [1]
				true, -- [2]
			},
		},
	},
}

E:RegisterProfile(name, profile)