local E, L, C = unpack(select(2, ...))

local name = "kgPanelsDB"
local profile = {
	["namespaces"] = {
		["LibDualSpec-1.0"] = {
		},
	},
	["global"] = {
		["version"] = 6,
		["artwork"] = {
			["bluecircles2"] = "\\\\Interface\\AddOns\\kgart\\bluecircles2.tga ",
			["Grunge3"] = "\\\\Interface\\AddOns\\kgart\\grunge3.tga",
			["flowery"] = "\\\\Interface\\AddOns\\kgart\\flowers.tga",
			["winter1"] = "\\\\Interface\\AddOns\\kgart\\winter.tga",
			["snow3"] = "\\\\Interface\\AddOns\\kgart\\snow3.tga",
			["bluecircles3"] = "\\\\Interface\\AddOns\\kgart\\bluecircles3.tga",
			["Circles3"] = "\\\\Interface\\AddOns\\kgart\\circles3.tga",
			["hearts"] = "\\\\Interface\\AddOns\\kgart\\heart.tga",
			["flowery3"] = "\\\\Interface\\AddOns\\kgart\\flowers3.tga",
			["winter2"] = "\\\\Interface\\AddOns\\kgart\\winter2.tga",
			["Grunge2"] = "\\\\Interface\\AddOns\\kgart\\grunge2.tga",
			["snow2"] = "\\\\Interface\\AddOns\\kgart\\snow2.tga",
			["Runes"] = "\\\\Interface\\AddOns\\kgart\\runes.tga",
			["Planets3"] = "\\\\Interface\\AddOns\\kgart\\planets3.tga",
			["Circles2"] = "\\\\Interface\\AddOns\\kgart\\circles2.tga",
			["Grunge"] = "\\\\Interface\\AddOns\\kgart\\grunge.tga",
			["flowery2"] = "\\\\Interface\\AddOns\\kgart\\flowers2.tga",
			["snow"] = "\\\\Interface\\AddOns\\kgart\\snow.tga",
			["winter3"] = "\\\\Interface\\AddOns\\kgart\\winter3.tga",
			["Planets2"] = "\\\\Interface\\AddOns\\kgart\\planets2.tga",
			["Circles"] = "\\\\Interface\\AddOns\\kgart\\circles.tga",
			["ElvUI Norm"] = "\\\\Interface\\\\Textures 3\\\\normTex2.tga",
			["bluecircles"] = "\\\\Interface\\AddOns\\kgart\\bluecircles.tga",
			["Runes3"] = "\\\\Interface\\AddOns\\kgart\\runes3.tga",
			["Planets"] = "\\\\Interface\\AddOns\\kgart\\planets.tga",
			["snow0"] = "\\\\Interface\\AddOns\\kgart\\snow000.tga",
			["hearts3"] = "\\\\Interface\\AddOns\\kgart\\heart3.tga",
			["Runes2"] = "\\\\Interface\\AddOns\\kgart\\runes2.tga",
		},
		["layouts"] = {
			["something else"] = {
			},
			["Something"] = {
				["Bars"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "UIParent",
					["bg_orientation"] = "HORIZONTAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "snow0",
					["anchor"] = "UIParent",
					["level"] = 0,
					["vert_tile"] = false,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["font"] = "Blizzard",
						["justifyH"] = "CENTER",
						["x"] = 0,
						["color"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = -8.584255444083199,
					["bg_alpha"] = 0.63,
					["border_edgeSize"] = 10,
					["height"] = 83.99999803191821,
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["horz_tile"] = false,
					["anchorTo"] = "CENTER",
					["scale"] = 2,
					["absolute_bg"] = {
						["LRy"] = 1,
						["LRx"] = 1,
						["ULx"] = 0,
						["ULy"] = 0,
						["URy"] = 0,
						["URx"] = 1,
						["LLx"] = 0,
						["LLy"] = 1,
					},
					["crop"] = false,
					["scripts"] = {
					},
					["bg_style"] = "NONE",
					["gradient_color"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["border_texture"] = "None",
					["width"] = 386.000011949068,
					["sub_level"] = 0,
					["bg_color"] = {
						["a"] = 0.6,
						["b"] = 0.3,
						["g"] = 0.3,
						["r"] = 0.3,
					},
					["mouse"] = false,
					["y"] = -262.6891144201283,
					["bg_insets"] = {
						["r"] = -4,
						["t"] = -4,
						["l"] = 4,
						["b"] = 4,
					},
				},
				["Default"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "UIParent",
					["bg_orientation"] = "HORIZONTAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "snow",
					["anchor"] = "UIParent",
					["level"] = 0,
					["vert_tile"] = false,
					["use_absolute_bg"] = false,
					["bg_blend"] = "BLEND",
					["text"] = {
						["y"] = 0,
						["x"] = 0,
						["justifyH"] = "CENTER",
						["font"] = "Blizzard",
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = -386.220635042357,
					["bg_alpha"] = 0.27,
					["border_edgeSize"] = 12,
					["height"] = 107.0000049904931,
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["horz_tile"] = false,
					["anchorTo"] = "CENTER",
					["scale"] = 2,
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URx"] = 1,
						["URy"] = 0,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["crop"] = false,
					["scripts"] = {
					},
					["bg_style"] = "NONE",
					["gradient_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_texture"] = "None",
					["width"] = 229.0000051310704,
					["sub_level"] = 0,
					["bg_insets"] = {
						["b"] = 4,
						["t"] = -4,
						["l"] = 4,
						["r"] = -4,
					},
					["mouse"] = false,
					["bg_color"] = {
						["a"] = 1,
						["r"] = 0.196078431372549,
						["g"] = 0.196078431372549,
						["b"] = 0.196078431372549,
					},
					["y"] = -249.711843445279,
				},
				["Other side"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "UIParent",
					["bg_orientation"] = "HORIZONTAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "snow2",
					["anchor"] = "UIParent",
					["level"] = 0,
					["vert_tile"] = false,
					["use_absolute_bg"] = false,
					["bg_blend"] = "ALPHAKEY",
					["text"] = {
						["y"] = 0,
						["x"] = 0,
						["justifyH"] = "CENTER",
						["font"] = "Blizzard",
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["y"] = -249.2439319996815,
					["bg_color"] = {
						["a"] = 1,
						["r"] = 0.9647058823529412,
						["g"] = 0.9647058823529412,
						["b"] = 0.9647058823529412,
					},
					["bg_alpha"] = 0.27,
					["border_edgeSize"] = 12,
					["height"] = 107.0000049904931,
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["horz_tile"] = false,
					["anchorTo"] = "CENTER",
					["scale"] = 2,
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URx"] = 1,
						["URy"] = 0,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["bg_insets"] = {
						["b"] = 4,
						["t"] = -4,
						["l"] = 4,
						["r"] = -4,
					},
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["r"] = 0.3098039215686275,
						["g"] = 1,
						["b"] = 0.3137254901960784,
					},
					["border_texture"] = "None",
					["width"] = 229.9999976101864,
					["sub_level"] = 0,
					["x"] = 377.0710475417569,
					["mouse"] = false,
					["rotation"] = 0,
					["crop"] = false,
				},
			},
			["For Real"] = {
			},
			["CUSTOM"] = {
			},
			["Stealth 2"] = {
			},
			["Neat"] = {
				["Bottom Gradient"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "UIParent",
					["bg_orientation"] = "VERTICAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Solid",
					["anchor"] = "UIParent",
					["level"] = 0,
					["use_absolute_bg"] = true,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["font"] = "Blizzard",
						["justifyH"] = "CENTER",
						["x"] = 0,
						["color"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = -193.3322246204679,
					["bg_alpha"] = 0,
					["border_edgeSize"] = 28,
					["height"] = 399.9999694824219,
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["scale"] = 1.02,
					["absolute_bg"] = {
						["LRy"] = 1,
						["LRx"] = 1,
						["ULx"] = 0,
						["ULy"] = 0,
						["URy"] = 0,
						["URx"] = 1,
						["LLx"] = 0,
						["LLy"] = 1,
					},
					["bg_insets"] = {
						["r"] = -4,
						["t"] = -4,
						["l"] = 4,
						["b"] = 4,
					},
					["scripts"] = {
					},
					["bg_style"] = "GRADIENT",
					["gradient_color"] = {
						["a"] = 0,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["border_color"] = {
						["a"] = 0,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["border_texture"] = "Blizzard Tooltip",
					["width"] = 2278,
					["y"] = -393.0384594896874,
					["bg_color"] = {
						["a"] = 1,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["mouse"] = false,
					["crop"] = false,
					["sub_level"] = 0,
				},
				["UI to Action"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOTRIGHTCORNER"] = true,
							["TOPRIGHTCORNER"] = true,
							["TOPLEFTCORNER"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["LEFT"] = true,
							["TOP"] = true,
							["BOT"] = true,
						},
					},
					["parent"] = "UIParent",
					["bg_orientation"] = "HORIZONTAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Black Gradient",
					["anchor"] = "UIParent",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["font"] = "Blizzard",
						["justifyH"] = "CENTER",
						["x"] = 0,
						["color"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["y"] = -456,
					["x"] = "0",
					["bg_alpha"] = 1,
					["border_edgeSize"] = 10,
					["height"] = "56",
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["absolute_bg"] = {
						["LRy"] = 1,
						["LRx"] = 1,
						["ULx"] = 0,
						["ULy"] = 0,
						["URx"] = 1,
						["URy"] = 0,
						["LLx"] = 0,
						["LLy"] = 1,
					},
					["crop"] = false,
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["border_color"] = {
						["a"] = 0,
						["b"] = 0.1568627450980392,
						["g"] = 0.1568627450980392,
						["r"] = 0.1568627450980392,
					},
					["border_texture"] = "Boarders A",
					["width"] = "624",
					["bg_insets"] = {
						["b"] = "0",
						["t"] = "0",
						["l"] = "0",
						["r"] = "0",
					},
					["bg_color"] = {
						["a"] = 0,
						["b"] = 0.2745098039215687,
						["g"] = 0.2745098039215687,
						["r"] = 0.2745098039215687,
					},
					["mouse"] = false,
					["rotation"] = 0,
					["sub_level"] = 0,
				},
				["Line Left"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOTRIGHTCORNER"] = true,
							["TOPRIGHTCORNER"] = true,
							["TOPLEFTCORNER"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["LEFT"] = true,
							["TOP"] = true,
							["BOT"] = true,
						},
					},
					["parent"] = "LeftChatDataPanel",
					["bg_orientation"] = "HORIZONTAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Black Gradient",
					["anchor"] = "LeftChatDataPanel",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["x"] = 0,
						["justifyH"] = "CENTER",
						["font"] = "BigNoodleTitling",
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = 127,
					["bg_alpha"] = 1,
					["border_edgeSize"] = 10,
					["height"] = "14",
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["scale"] = 1,
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URx"] = 1,
						["URy"] = 0,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["bg_insets"] = {
						["b"] = "0",
						["t"] = "0",
						["l"] = "0",
						["r"] = "0",
					},
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["r"] = 0.1568627450980392,
						["g"] = 0.1568627450980392,
						["b"] = 0.1568627450980392,
					},
					["border_texture"] = "Boarders A",
					["width"] = "500",
					["sub_level"] = 3,
					["crop"] = false,
					["mouse"] = false,
					["bg_color"] = {
						["a"] = 0.300000011920929,
						["r"] = 0.2745098039215687,
						["g"] = 0.2745098039215687,
						["b"] = 0.2745098039215687,
					},
					["y"] = 0,
				},
				["TITAN"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "UIParent",
					["bg_orientation"] = "VERTICAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Solid",
					["anchor"] = "UIParent",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["x"] = 0,
						["justifyH"] = "CENTER",
						["font"] = "Blizzard",
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = 12.99993983292822,
					["bg_alpha"] = 1,
					["border_edgeSize"] = 18,
					["height"] = 26.99999486892962,
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URy"] = 0,
						["URx"] = 1,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["crop"] = false,
					["scripts"] = {
					},
					["bg_style"] = "GRADIENT",
					["gradient_color"] = {
						["a"] = 0,
						["r"] = 0.2313725490196079,
						["g"] = 0.2313725490196079,
						["b"] = 0.2313725490196079,
					},
					["border_color"] = {
						["a"] = 0,
						["r"] = 0.2078431372549019,
						["g"] = 0.2078431372549019,
						["b"] = 0.2078431372549019,
					},
					["border_texture"] = "Boarders A",
					["width"] = "950",
					["sub_level"] = 0,
					["bg_insets"] = {
						["r"] = -4,
						["t"] = -4,
						["l"] = 4,
						["b"] = 4,
					},
					["mouse"] = false,
					["y"] = "-575",
					["bg_color"] = {
						["a"] = 0,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
				},
				["UI to Action1"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["TOPLEFTCORNER"] = true,
							["RIGHT"] = true,
							["BOTLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "UIParent",
					["sub_level"] = 0,
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Black Gradient",
					["anchor"] = "LeftChatDataPanel",
					["level"] = 20,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["x"] = 0,
						["justifyH"] = "CENTER",
						["font"] = "Blizzard",
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["y"] = 0,
					["x"] = "686",
					["bg_alpha"] = 1,
					["border_edgeSize"] = 10,
					["height"] = "56",
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URy"] = 0,
						["URx"] = 1,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["crop"] = false,
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["r"] = 0.1568627450980392,
						["g"] = 0.1568627450980392,
						["b"] = 0.1568627450980392,
					},
					["border_texture"] = "Boarders A",
					["width"] = "624",
					["bg_orientation"] = "HORIZONTAL",
					["rotation"] = 0,
					["mouse"] = false,
					["bg_color"] = {
						["a"] = 0.300000011920929,
						["r"] = 0.2745098039215687,
						["g"] = 0.2745098039215687,
						["b"] = 0.2745098039215687,
					},
					["bg_insets"] = {
						["r"] = "0",
						["t"] = "0",
						["l"] = "0",
						["b"] = "0",
					},
				},
				["Combo Bar"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOTRIGHTCORNER"] = true,
							["TOPRIGHTCORNER"] = true,
							["TOPLEFTCORNER"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["LEFT"] = true,
							["TOP"] = true,
							["BOT"] = true,
						},
					},
					["parent"] = "ComergyMainFrame",
					["sub_level"] = 4,
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "ElvUI Norm",
					["anchor"] = "ComergyMainFrame",
					["level"] = 3,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["x"] = 0,
						["justifyH"] = "CENTER",
						["font"] = "BigNoodleTitling",
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = 0,
					["bg_alpha"] = 1,
					["border_edgeSize"] = 10,
					["height"] = "38",
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["scale"] = 1,
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URx"] = 1,
						["URy"] = 0,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["bg_insets"] = {
						["b"] = "0",
						["t"] = "0",
						["l"] = "0",
						["r"] = "0",
					},
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["r"] = 0.1568627450980392,
						["g"] = 0.1568627450980392,
						["b"] = 0.1568627450980392,
					},
					["border_texture"] = "Boarders A",
					["width"] = "230",
					["bg_orientation"] = "HORIZONTAL",
					["crop"] = false,
					["mouse"] = false,
					["bg_color"] = {
						["a"] = 1,
						["r"] = 0.2196078431372549,
						["g"] = 0.2196078431372549,
						["b"] = 0.2196078431372549,
					},
					["y"] = "0",
				},
				["Time"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "UIParent",
					["bg_orientation"] = "VERTICAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Solid",
					["anchor"] = "UIParent",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["x"] = 0,
						["justifyH"] = "CENTER",
						["font"] = "Blizzard",
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = "887",
					["bg_alpha"] = 1,
					["border_edgeSize"] = 18,
					["height"] = 28.00000759117262,
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URy"] = 0,
						["URx"] = 1,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["crop"] = false,
					["scripts"] = {
					},
					["bg_style"] = "GRADIENT",
					["gradient_color"] = {
						["a"] = 0,
						["r"] = 0.1764705882352941,
						["g"] = 0.1764705882352941,
						["b"] = 0.1764705882352941,
					},
					["border_color"] = {
						["a"] = 0,
						["r"] = 0.1843137254901961,
						["g"] = 0.1843137254901961,
						["b"] = 0.1843137254901961,
					},
					["border_texture"] = "Boarders A",
					["width"] = "110",
					["sub_level"] = 0,
					["bg_insets"] = {
						["r"] = -4,
						["t"] = -4,
						["l"] = 4,
						["b"] = 4,
					},
					["mouse"] = false,
					["y"] = "-574",
					["bg_color"] = {
						["a"] = 0,
						["r"] = 0,
						["g"] = 0,
						["b"] = 0,
					},
				},
				["UI Mini"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "BT4Button85",
					["sub_level"] = 0,
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Solid",
					["anchor"] = "BT4Button85",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["font"] = "Blizzard",
						["justifyH"] = "CENTER",
						["x"] = 0,
						["color"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = 74,
					["bg_alpha"] = 1,
					["border_edgeSize"] = 18,
					["height"] = "54",
					["tiling"] = false,
					["strata"] = "LOW",
					["anchorTo"] = "CENTER",
					["scale"] = 1,
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URy"] = 0,
						["URx"] = 1,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["bg_insets"] = {
						["r"] = -4,
						["t"] = -4,
						["l"] = 4,
						["b"] = 4,
					},
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 0.4000000357627869,
						["b"] = 0,
						["g"] = 0,
						["r"] = 0,
					},
					["border_color"] = {
						["a"] = 1,
						["b"] = 0.1215686274509804,
						["g"] = 0.1215686274509804,
						["r"] = 0.1215686274509804,
					},
					["border_texture"] = "Boarders A",
					["width"] = "205",
					["y"] = "0",
					["bg_color"] = {
						["a"] = 0.6500000059604645,
						["b"] = 0.1450980392156863,
						["g"] = 0.1450980392156863,
						["r"] = 0.1450980392156863,
					},
					["mouse"] = false,
					["crop"] = false,
					["bg_orientation"] = "HORIZONTAL",
				},
				["FX"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOTRIGHTCORNER"] = true,
							["TOPRIGHTCORNER"] = true,
							["TOPLEFTCORNER"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["LEFT"] = true,
							["TOP"] = true,
							["BOT"] = true,
						},
					},
					["parent"] = "UIParent",
					["bg_orientation"] = "HORIZONTAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Solid",
					["anchor"] = "LeftChatDataPanel",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "BLEND",
					["text"] = {
						["y"] = 0,
						["font"] = "Blizzard",
						["justifyH"] = "CENTER",
						["x"] = 0,
						["color"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["y"] = "0",
					["x"] = "686",
					["bg_alpha"] = 1,
					["border_edgeSize"] = 10,
					["height"] = "22",
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URy"] = 0,
						["URx"] = 1,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["crop"] = false,
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["b"] = 0.1568627450980392,
						["g"] = 0.1568627450980392,
						["r"] = 0.1568627450980392,
					},
					["border_texture"] = "Boarders A",
					["width"] = 588,
					["bg_insets"] = {
						["r"] = "0",
						["t"] = "0",
						["l"] = "0",
						["b"] = "0",
					},
					["bg_color"] = {
						["a"] = 1,
						["b"] = 0.2196078431372549,
						["g"] = 0.2196078431372549,
						["r"] = 0.2196078431372549,
					},
					["mouse"] = false,
					["rotation"] = 0,
					["sub_level"] = 0,
				},
				["Player Cast Bar"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "Quartz3CastBarPlayer",
					["sub_level"] = 0,
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Solid",
					["anchor"] = "Quartz3CastBarPlayer",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "BLEND",
					["text"] = {
						["y"] = 0,
						["x"] = 0,
						["justifyH"] = "CENTER",
						["font"] = "Blizzard",
						["color"] = {
							["a"] = 1,
							["r"] = 1,
							["g"] = 1,
							["b"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = 0,
					["bg_alpha"] = 1,
					["border_edgeSize"] = 16,
					["height"] = 24.99992893818965,
					["tiling"] = false,
					["strata"] = "HIGH",
					["anchorTo"] = "CENTER",
					["absolute_bg"] = {
						["LLy"] = 1,
						["LLx"] = 0,
						["LRy"] = 1,
						["LRx"] = 1,
						["URx"] = 1,
						["URy"] = 0,
						["ULy"] = 0,
						["ULx"] = 0,
					},
					["crop"] = false,
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["border_texture"] = "None",
					["width"] = 220.0000908129169,
					["bg_insets"] = {
						["b"] = 4,
						["t"] = -4,
						["l"] = 4,
						["r"] = -4,
					},
					["bg_orientation"] = "HORIZONTAL",
					["mouse"] = false,
					["bg_color"] = {
						["a"] = 1,
						["r"] = 0.5294117647058824,
						["g"] = 0.5294117647058824,
						["b"] = 0.5294117647058824,
					},
					["y"] = 0,
				},
				["Line Right"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["TOPLEFTCORNER"] = true,
							["RIGHT"] = true,
							["BOTLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "RightChatDataPanel",
					["bg_orientation"] = "HORIZONTAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Black Gradient",
					["anchor"] = "RightChatDataPanel",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "DISABLE",
					["text"] = {
						["y"] = 0,
						["font"] = "BigNoodleTitling",
						["justifyH"] = "CENTER",
						["x"] = 0,
						["color"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = -127,
					["bg_alpha"] = 1,
					["border_edgeSize"] = 10,
					["height"] = "14",
					["tiling"] = false,
					["strata"] = "BACKGROUND",
					["anchorTo"] = "CENTER",
					["scale"] = 1,
					["absolute_bg"] = {
						["ULx"] = 0,
						["ULy"] = 0,
						["LLy"] = 1,
						["LLx"] = 0,
						["URy"] = 0,
						["URx"] = 1,
						["LRx"] = 1,
						["LRy"] = 1,
					},
					["bg_insets"] = {
						["r"] = "0",
						["t"] = "0",
						["l"] = "0",
						["b"] = "0",
					},
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["b"] = 0.1568627450980392,
						["g"] = 0.1568627450980392,
						["r"] = 0.1568627450980392,
					},
					["border_texture"] = "Boarders A",
					["width"] = "500",
					["y"] = 0,
					["bg_color"] = {
						["a"] = 0.300000011920929,
						["b"] = 0.2745098039215687,
						["g"] = 0.2745098039215687,
						["r"] = 0.2745098039215687,
					},
					["mouse"] = false,
					["crop"] = false,
					["sub_level"] = 3,
				},
				["Target Cast Bar"] = {
					["border_advanced"] = {
						["enable"] = false,
						["show"] = {
							["BOT"] = true,
							["TOPRIGHTCORNER"] = true,
							["LEFT"] = true,
							["BOTLEFTCORNER"] = true,
							["RIGHT"] = true,
							["TOPLEFTCORNER"] = true,
							["TOP"] = true,
							["BOTRIGHTCORNER"] = true,
						},
					},
					["parent"] = "Quartz3CastBarTarget",
					["bg_orientation"] = "HORIZONTAL",
					["anchorFrom"] = "CENTER",
					["hflip"] = false,
					["vflip"] = false,
					["tileSize"] = 0,
					["bg_texture"] = "Solid",
					["anchor"] = "Quartz3CastBarTarget",
					["level"] = 0,
					["use_absolute_bg"] = false,
					["bg_blend"] = "BLEND",
					["text"] = {
						["y"] = 0,
						["font"] = "Blizzard",
						["justifyH"] = "CENTER",
						["x"] = 0,
						["color"] = {
							["a"] = 1,
							["b"] = 1,
							["g"] = 1,
							["r"] = 1,
						},
						["text"] = "",
						["justifyV"] = "MIDDLE",
						["size"] = 12,
					},
					["rotation"] = 0,
					["x"] = 0,
					["bg_alpha"] = 1,
					["border_edgeSize"] = 16,
					["height"] = 24.99992893818965,
					["tiling"] = false,
					["strata"] = "HIGH",
					["anchorTo"] = "CENTER",
					["absolute_bg"] = {
						["LRy"] = 1,
						["LRx"] = 1,
						["ULx"] = 0,
						["ULy"] = 0,
						["URy"] = 0,
						["URx"] = 1,
						["LLx"] = 0,
						["LLy"] = 1,
					},
					["bg_insets"] = {
						["r"] = -4,
						["t"] = -4,
						["l"] = 4,
						["b"] = 4,
					},
					["scripts"] = {
					},
					["bg_style"] = "SOLID",
					["gradient_color"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["border_color"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["border_texture"] = "None",
					["width"] = 220.0000908129169,
					["y"] = 0,
					["bg_color"] = {
						["a"] = 1,
						["b"] = 0.3529411764705882,
						["g"] = 0.3529411764705882,
						["r"] = 0.3529411764705882,
					},
					["mouse"] = false,
					["crop"] = false,
					["sub_level"] = 0,
				},
			},
		},
		["layout_deps"] = {
			["Neat"] = {
				["Combo Bars"] = "",
			},
		},
		["border"] = {
			["Neav"] = "\\\\Interface\\\\Textures 3\\\\Neav.tga",
			["ElvUI Dark"] = "\\\\Interface\\\\Textures 3\\\\Border-ElvUI-New",
			["Roth"] = "\\\\Interface\\\\Textures 3\\\\Roth.tga",
			["Caith"] = "\\\\Interface\\\\Textures 3\\\\Caith.tga",
			["Boarders A"] = "\\\\Interface\\\\Textures 3\\\\Caith White.tga",
			["Roth White"] = "\\\\Interface\\\\Textures 3\\\\Roth White.tga",
		},
		["defaultPanel"] = {
			["anchorFrom"] = "BOTTOMRIGHT",
			["bg_texture"] = "Blizzard Dialog Background",
			["level"] = 9,
			["bg_blend"] = "ALPHAKEY",
			["y"] = 88,
			["bg_color"] = {
				["a"] = 0.6000000238418579,
				["b"] = 0,
				["g"] = 0.01568627450980392,
				["r"] = 0.3019607843137255,
			},
			["border_edgeSize"] = 3,
			["height"] = "90",
			["strata"] = "MEDIUM",
			["anchorTo"] = "BOTTOMLEFT",
			["scale"] = 2,
			["bg_style"] = "NONE",
			["border_texture"] = "None",
			["width"] = "90",
			["x"] = 66,
		},
	},
	["profileKeys"] = {
		["Alieyna - Dunemaul"] = "Default",
		["Gho - Ysondre"] = "Default",
		["Instaq - Laughing Skull"] = "Default",
		["Rhodara - Blackhand"] = "Default",
		["Ellence - Blade's Edge"] = "Default",
		["Letheliarah - Khadgar"] = "Default",
		["Ghorde - Kel'Thuzad"] = "Default",
		["Praedatør - Kel'Thuzad"] = "Default",
		["Nymue - Dark Iron"] = "Default",
		["Jirisa - Shadowsong"] = "Default",
		["Alaule - Garrosh"] = "Default",
		["Eliena - Mug'thol"] = "Default",
		["Aliena - Dark Iron"] = "Default",
		["Frustration - Mug'thol"] = "Default",
		["Maulls - Kel'Thuzad"] = "Default",
		["Aliena - Mug'thol"] = "Aliena",
		["Geduld - Executus"] = "Default",
		["Iheartdktank - Shadowmoon"] = "Default",
		["Glados - Mug'thol"] = "Default",
		["Mondschimmer - Dark Iron"] = "Default",
		["Clashadrey - Tichondrius"] = "Default",
		["Twocents - Kel'Thuzad"] = "Default",
		["Carritrie - Dalaran"] = "Default",
		["Annai - Mug'thol"] = "Default",
		["Miriamel - Dark Iron"] = "Default",
		["Lorania - Firetree"] = "Default",
		["Saonserey - Dark Iron"] = "Default",
		["Kazbek - Lightbringer"] = "Default",
		["Bovinehymn - Mug'thol"] = "Default",
		["Pistazie - Mug'thol"] = "Default",
		["Snô - Kel'Thuzad"] = "OPUI 1200",
		["Yaniana - Andorhal"] = "Default",
		["Annai - Dark Iron"] = "Default",
		["Alyena - Dunemaul"] = "Default",
		["Anorilae - Mug'thol"] = "Default",
		["Evayne - Dark Iron"] = "Default",
		["Artery - Mug'thol"] = "Default",
		["Saonserey - Vashj"] = "Default",
		["Geduld - Dark Iron"] = "Default",
		["Miriamele - Mug'thol"] = "Default",
		["Marissia - Rexxar"] = "Default",
		["Löckness - Laughing Skull"] = "Default",
		["Ðreaded - Kel'Thuzad"] = "Dreaded",
		["Powlk - Arygos"] = "Default",
		["Miriamel - Executus"] = "Default",
		["Pubick - Kel'Thuzad"] = "Pubick - Kel'Thuzad",
		["Saonserey - Drak'thul"] = "Default",
		["Koredishton - Kel'Thuzad"] = "Default",
		["Opacus - Kel'Thuzad"] = "OPUI",
		["Aliena - Garrosh"] = "Default",
		["Saonserey - Mug'thol"] = "Default",
		["Tralsong - Argent Dawn"] = "Default",
		["Ezozela - Dark Iron"] = "Default",
		["Melicelicity - Drenden"] = "Default",
		["Instaque - Kel'Thuzad"] = "Default",
		["Ingenuity - Thrall"] = "Default",
		["Halvinravis - Terenas"] = "Default",
		["Cuteplusplus - Mug'thol"] = "Default",
		["Semele - Thrall"] = "Default",
		["Shãmwøw - Kel'Thuzad"] = "Default",
		["Mairisena - Kilrogg"] = "Default",
		["Lichtgestalt - Dark Iron"] = "Default",
		["Eredrillin - Kil'jaeden"] = "Default",
		["Mileiance - Zuluhed"] = "Default",
		["Ponk - Kel'Thuzad"] = "OPUI",
	},
	["profiles"] = {
		["Default"] = {
			["layout"] = "Neat",
		},
		["OPUI"] = {
			["layout"] = "Neat",
		},
	},
}

E:RegisterProfile(name, profile)
